- name: Set hostname
  hostname:
    name: elkstack

- name: Setup NTP time sync
  package: name={{ item }} state=installed
  with_items:
    - ntpdate
    - ntp-doc
- service:
    name: ntpd
    state: started
    enabled: yes

- yum:
    name: '*'
    state: latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
- package: name={{item}} state=installed
  with_items:
    - python-pip
- pip:
    name: pexpect
    version: 3.3


- name: Add Elastic repo
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
- yum_repository:
    name: elastic.co
    description: Elasticsearch repository for 5.x packages
    baseurl: https://artifacts.elastic.co/packages/5.x/yum
    enabled: yes
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Install/Setup Elasticsearch
  yum: name={{item}} state=installed
  with_items:
    - elasticsearch
    - java
    - curl
- service:
    name: elasticsearch
    state: started
    enabled: yes

- name: Install/Setup Logstash
  yum:
    name: logstash
    state: installed

- template:
    src: conf/logstash/02-beats-input.conf
    dest: /etc/logstash/conf.d/02-input-beats.conf
    owner: root
    group: root
    mode: '0600'
- template:
    src: conf/logstash/30-elasticsearch-output.conf
    dest: /etc/logstash/conf.d/30-elasticsearch-output.conf
    owner: root
    group: root
    mode: '0600'
- service:
    name: logstash
    state: started
    enabled: yes
- name: Install/Setup Kibana
  yum:
    name: kibana
    state: installed
- service:
    name: kibana
    state: restarted
    enabled: yes

- name: Install/Setup Nginx + OpenSSL
  yum: name={{item}} state=installed
  with_items:
    - nginx
    - httpd-tools
- expect:
    command: 'htpasswd -c /etc/nginx/htpasswd.users {{ kibana_user }}'
    responses:
      (?i)password: "{{ kibana_pass }}"
- shell: cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak
- template:
    src: conf/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0600'
- file:
    path: /etc/nginx/ssl
    state: directory
    mode: 0755
- shell: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
- shell: openssl req -new -nodes -x509 -days 3650 -subj "/C=US/ST=NY/L=Rochester/O=None/CN={{ kibana_domain }}" -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt

- template:
    src: conf/nginx/nginx_kibana.conf
    dest: /etc/nginx/conf.d/nginx_kibana.conf
    owner: root
    group: root
    mode: '0600'

- service:
    name: nginx
    state: started
    enabled: yes

- name: Set SElinux to permissive
  selinux:
    policy: targeted
    state: permissive

- name: Install/Setup FireallD
  yum:
    name: firewalld
    state: latest
- service:
    name: firewalld
    state: started
    enabled: yes
- firewalld:
    service: ssh
    permanent: true
    state: enabled
- firewalld:
    service: http
    permanent: true
    state: enabled
- firewalld:
    service: https
    permanent: true
    state: enabled
- firewalld:
    port: 5044/tcp
    permanent: true
    state: enabled
- service:
    name: firewalld
    state: restarted
    enabled: yes
